name: Daily Crypto Pipeline

# ★ Geef de workflow schrijfrechten op repo-inhoud
permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "15 6 * * *"   # elke dag 06:15 UTC

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (with token)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # nodig om te kunnen committen/pushen
          persist-credentials: true  # gebruikt automatisch GITHUB_TOKEN

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pipeline
        run: python run.py

      - name: Upload reports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: crypto-reports

