          path: |
            data/reports/latest.csv
            data/reports/latest.json
            data/reports/scores_latest.csv
            data/reports/scores_latest.json
            data/reports/top5_latest.md

      - name: Commit reports back to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # eerst rebase om conflicts te voorkomen
          git pull --rebase
          # force add omdat .gitignore *.csv/json negeert
          git add -f data/reports/*.csv data/reports/*.json data/reports/*.md || true
          git commit -m "daily scorecard" || echo "no changes"
          git push origin HEAD:main
name: Daily Crypto Pipeline

# ★ Geef de workflow schrijfrechten op repo-inhoud
permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "15 6 * * *"   # elke dag 06:15 UTC

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (with token)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # nodig om te kunnen committen/pushen
          persist-credentials: true  # gebruikt automatisch GITHUB_TOKEN

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pipeline
        run: python run.py

      - name: Upload reports as artifact
        uses: actions/upload-artifact@v4
        with:
          name: crypto-reports
          path: |
            data/reports/latest.csv
            data/reports/latest.json

      - name: Commit reports back to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/reports/*.csv data/reports/*.json || true
          git commit -m "daily scorecard" || echo "no changes"
          # kleine veiligheidsmarge tegen race-conflict
          git pull --rebase
          git push origin HEAD:main
