name: Daily Crypto Pipeline

on:
  workflow_dispatch:      # handmatig starten
  schedule:
    - cron: "0 8 * * *"   # elke dag 08:00 UTC

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (best effort)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pipeline
        run: |
          python run.py

